# Generated by Django 5.1.3 on 2024-12-09 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('taskDescription', models.TextField(max_length=1500)),
                ('publishedAt', models.DateTimeField(auto_now=True)),
                ('taskDeadline', models.DateTimeField(auto_now=True)),
                ('taskStatus', models.TextField(choices=[('new', 'New'), ('inprogress', 'Inprogress'), ('finished', 'Finished'), ('canceled', 'Canceled')], max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
