# Generated by Django 4.2.17 on 2024-12-21 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_task_slug_alter_task_publishedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to=settings.AUTH_USER_MODEL),
        ),
    ]
