# Generated by Django 4.2.17 on 2024-12-21 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('experience', models.TextField(max_length=100)),
                ('desired_price', models.IntegerField()),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='task.task')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='applicants',
            field=models.ManyToManyField(related_name='applied_tasks', through='task.Apply', to=settings.AUTH_USER_MODEL),
        ),
    ]
