# Generated by Django 4.2.17 on 2024-12-20 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0006_alter_task_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='applicant',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='applicants',
            field=models.ManyToManyField(related_name='applied_tasks', through='task.Apply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='publishedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
