# Generated by Django 4.2.17 on 2024-12-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_apply_applicant_task_applicants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='experience',
            field=models.TextField(default=9, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apply',
            name='required_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
