# Generated by Django 4.2.17 on 2024-12-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_apply_applicant_remove_task_applicants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='disability_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='has_disability',
            field=models.BooleanField(default=False),
        ),
    ]
