name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest pytest-django bandit mypy coverage
      working-directory: ./src

    - name: Lint code
      run: |
        flake8 .
        bandit -r .
      working-directory: ./src

    - name: Check database migrations
      run: |
        python manage.py makemigrations --check --dry-run
      working-directory: ./src

    - name: Run tests
      run: |
        python manage.py test
        coverage run --source='.' manage.py test
        coverage report
      working-directory: ./src

    - name: Archive coverage results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: src/htmlcov
