name: Django CI Test (Windows)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: windows-latest  # Use a Windows runner

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.8'

    - name: Install dependencies
      run: |
        python -m venv venv             # Create a virtual environment
        .\venv\Scripts\activate         # Activate the virtual environment
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Install dependencies

    - name: Run migrations
      run: |
        .\venv\Scripts\activate         # Activate the virtual environment
        cd JobFinder/src                # Navigate to JobFinder/src where manage.py is
        python manage.py makemigrations
        python manage.py migrate

    - name: Run Tests
      run: |
        .\venv\Scripts\activate         # Activate the virtual environment
        cd JobFinder/src                # Navigate to JobFinder/src
        python manage.py test
