name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.8'

      - name: Run migrations
        run: |
          pip install -r requirements.txt
          .\venv\Scripts\activate              # Activate the virtual environment
          cd JobFinder\src                     # Navigate to the directory with manage.py
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: |
          .\venv\Scripts\activate              # Activate the virtual environment
          cd JobFinder\src                     # Navigate to the directory with manage.py
          python manage.py test user

